apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends-svc
    # tag: alpine
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: {{ .Values.service.protocol }} 
    targetPort: {{ .Values.service.targetPort }} 
  selector:
    app: techtrends-svc
    # tag: alpine
  type: {{ .Values.service.type }} 
