namespace:
  name: staging
 
service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: dinhtin12/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPort: 3111

livenessProbe: /healthz
livenessProbePort: 3111
readinessProbe: /healthz
readinessProbePort: 3111

##
# namespace: staging
# service-port: 5111
# replicaCount: 3
# resources: 
#   requests:
#     memory: 90Mi
#     cpu: 300m
#   limits:
#     memory: 128Mi
#     cpu: 500m
