namespace:
  name: prod
 
service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: dinhtin12/techtrends 
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

containerPort: 3111

livenessProbe: /healthz
livenessProbePort: 3111
readinessProbe: /healthz
readinessProbePort: 3111

#####

# namespace: prod
# service-port: 7111
# image-pullPolicy: Always
# replicaCount: 5
# resources:
#   requests:
#     memory: 128Mi
#     cpu: 350m
#   limits:
#     memory: 256Mi
#     cup: 500m